# Generated by Django 5.0.4 on 2024-04-25 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="first_name",
            new_name="fullName",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
