# Generated by Django 5.0.4 on 2024-04-25 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_first_name_user_fullname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tfa_secret",
        ),
    ]
