services:
  api:
    container_name: dj_admin_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - '.:/app'
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
  db:
    container_name: dj_admin_db
    image: postgres:16.2
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./.pgdata:/var/lib/postgresql/data # Volume for persisting PostgreSQL data
    ports:
      - 54324:5432